version: "3.8"
services:
  CONTAINER_NAME:
    container_name: ${CONTAINER_NAME:-CONTAINER_NAME}
    build: .
    image: ${IMAGE_NAME:-swoole-mongodb-redis}
    volumes:
      - ${VOLUMES_HYPERF_PATH:-/saas/CONTAINER_NAME}:/server/hyperf
      - ${VOLUMES_MONGODB_DATABASES_PATH:-/server/docker-volumes/CONTAINER_NAME/data/mongodb/databases}:/server/data/mongodb/databases
      - ${VOLUMES_MONGODB_LOGS_PATH:-/server/docker-volumes/CONTAINER_NAME/data/mongodb/logs}:/server/data/mongodb/logs
      - ${VOLUMES_SUPERVISOR_LOGS_PATH:-/server/docker-volumes/CONTAINER_NAME/data/supervisor/logs}:/server/data/supervisor/logs
      - ${VOLUMES_REDIS_DATE_PATH:-/server/docker-volumes/CONTAINER_NAME/data/redis}:/server/data/redis
      - ${VOLUMES_CONFIG_PATH:-/server/docker-volumes/CONTAINER_NAME/config}:/server/config
      - ${VOLUMES_CONFIG_SUPERVISOR_PATH:-/server/docker-volumes/CONTAINER_NAME/config/supervisor}:/etc/supervisor/conf.d
    networks:
      - home-club
    ports:
      - ${PORT_MONGODB:-"27017:27017"}
      - ${PORT_REDIS:-"6379:6379"}
networks:
  home-club:
    external: true